<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Zenvera.AiExamples.Rag.Tests</RootNamespace>
    <AssemblyName>Zenvera.AiExamples.Rag.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Rag\Zenvera.AiExamples.Rag.ManualConsoleHost\Zenvera.AiExamples.Rag.ManualConsoleHost.csproj" />
  </ItemGroup>
</Project>
